# Generated by Django 3.0.6 on 2020-06-19 11:59

import accounts.managers
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=30, verbose_name='last name')),
                ('other_name', models.CharField(blank=True, max_length=30, verbose_name='other names')),
                ('stage_name', models.CharField(blank=True, max_length=35, verbose_name='stage name')),
                ('phone', models.CharField(blank=True, max_length=15, verbose_name='phone number')),
                ('whatsapp_phone', models.CharField(blank=True, max_length=15, verbose_name='whatsapp')),
                ('music_class', models.CharField(blank=True, max_length=225)),
                ('company_name', models.CharField(max_length=55)),
                ('nationality', models.CharField(blank=True, max_length=35, verbose_name='Nationality')),
                ('sor', models.CharField(blank=True, max_length=225, verbose_name='state of residence')),
                ('lga', models.CharField(blank=True, max_length=225, verbose_name='local government area')),
                ('address', models.CharField(blank=True, max_length=225, verbose_name='address')),
                ('dob', models.DateField(null=True)),
                ('is_active', models.BooleanField(default=False, verbose_name='active')),
                ('change_password', models.BooleanField(default=False, verbose_name='change password')),
                ('verified', models.BooleanField(default=False, verbose_name='verify email')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='date joined')),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('objects', accounts.managers.ArtistManager()),
            ],
        ),
        migrations.CreateModel(
            name='OTP',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phone', models.IntegerField()),
                ('counter', models.IntegerField(default=0)),
                ('verified', models.BooleanField(default=False)),
                ('expiry', models.DateTimeField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserPhoto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(null=True, upload_to='files/profile-pictures')),
                ('artist', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Artist')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('account_number', models.CharField(blank=True, max_length=19, null=True)),
                ('bank_name', models.CharField(blank=True, max_length=75, null=True)),
                ('bank_code', models.CharField(blank=True, max_length=10, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('artist', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.Artist')),
            ],
        ),
        migrations.CreateModel(
            name='ArtistStorage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('used_space', models.FloatField(default=0.0)),
                ('total_space', models.FloatField(default=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('artist', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.Artist')),
            ],
        ),
    ]
