# Generated by Django 4.2.3 on 2023-09-20 20:52

import accounts.managers
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import utils.helper
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Artist",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="email address"
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=30, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=30, verbose_name="last name"
                    ),
                ),
                (
                    "other_names",
                    models.CharField(
                        blank=True, max_length=30, verbose_name="other names"
                    ),
                ),
                (
                    "stage_name",
                    models.CharField(
                        blank=True, max_length=35, verbose_name="stage name"
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        max_length=15, unique=True, verbose_name="phone number"
                    ),
                ),
                ("bio", models.CharField(blank=True, max_length=225, null=True)),
                ("music_class", models.CharField(blank=True, max_length=225)),
                ("company_name", models.CharField(blank=True, max_length=55)),
                (
                    "sor",
                    models.CharField(
                        blank=True, max_length=225, verbose_name="state of residence"
                    ),
                ),
                (
                    "lga",
                    models.CharField(
                        blank=True,
                        max_length=225,
                        null=True,
                        verbose_name="local government area",
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        blank=True, max_length=225, verbose_name="address"
                    ),
                ),
                (
                    "postal_code",
                    models.CharField(
                        blank=True, max_length=8, null=True, verbose_name="Postal Code"
                    ),
                ),
                (
                    "country",
                    models.CharField(
                        blank=True, max_length=35, null=True, verbose_name="Country"
                    ),
                ),
                (
                    "country_code",
                    models.CharField(
                        blank=True, max_length=5, verbose_name="Country Code"
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        blank=True, max_length=25, null=True, verbose_name="State"
                    ),
                ),
                (
                    "city",
                    models.CharField(
                        blank=True, max_length=75, null=True, verbose_name="cite"
                    ),
                ),
                ("dob", models.DateField(null=True)),
                (
                    "is_active",
                    models.BooleanField(default=False, verbose_name="active"),
                ),
                (
                    "change_password",
                    models.BooleanField(default=False, verbose_name="change password"),
                ),
                (
                    "verified",
                    models.BooleanField(default=False, verbose_name="verify email"),
                ),
                (
                    "phone_verified",
                    models.BooleanField(default=False, verbose_name="verify phone"),
                ),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(auto_now_add=True, verbose_name="date joined"),
                ),
            ],
            options={
                "abstract": False,
            },
            managers=[
                ("objects", accounts.managers.ArtistManager()),
            ],
        ),
        migrations.CreateModel(
            name="OTP",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("phone", models.BigIntegerField()),
                ("counter", models.IntegerField(default=0)),
                ("verified", models.BooleanField(default=False)),
                ("expiry", models.DateTimeField()),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="UserPhoto",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to=utils.helper.redefinedFileName
                    ),
                ),
                (
                    "artist",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.artist",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StaffProfile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("role", models.CharField(blank=True, max_length=45, null=True)),
                ("change_password", models.BooleanField(default=False)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BankAccount",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "account_number",
                    models.CharField(blank=True, max_length=19, null=True),
                ),
                ("bank_name", models.CharField(blank=True, max_length=75, null=True)),
                ("bank_code", models.CharField(blank=True, max_length=25, null=True)),
                ("bank_iban", models.CharField(blank=True, max_length=25, null=True)),
                ("bank_swift", models.CharField(blank=True, max_length=25, null=True)),
                ("route_no", models.CharField(blank=True, max_length=25, null=True)),
                (
                    "bank_branch",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "recipient_code",
                    models.CharField(blank=True, max_length=25, null=True),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "artist",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.artist",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ArtistStorage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("used_space", models.FloatField(default=0.0)),
                ("total_space", models.FloatField(default=200)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "artist",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.artist",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ArtistMeta",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "eveara_artist_id",
                    models.CharField(blank=True, max_length=11, null=True),
                ),
                (
                    "eveara_user_id",
                    models.CharField(blank=True, max_length=40, null=True),
                ),
                ("last_updated", models.DateTimeField(auto_now=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "artist",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.artist",
                    ),
                ),
            ],
        ),
    ]
