# Generated by Django 3.0.6 on 2020-06-23 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artist',
            old_name='other_name',
            new_name='other_names',
        ),
    ]
