# Generated by Django 3.0.6 on 2020-06-23 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200623_0422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='company_name',
            field=models.CharField(blank=True, max_length=55),
        ),
    ]
