# Generated by Django 3.0.6 on 2020-07-07 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20200707_0956'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffprofile',
            name='image',
            field=models.ImageField(null=True, upload_to='files/profile-pictures/admin/'),
        ),
        migrations.AlterField(
            model_name='userphoto',
            name='image',
            field=models.ImageField(null=True, upload_to='files/profile-pictures/artist/'),
        ),
    ]
