# Generated by Django 2.2.10 on 2020-07-13 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_userphoto_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='phone_verified',
            field=models.BooleanField(default=False, verbose_name='verify phone'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='phone',
            field=models.CharField(max_length=15, unique=True, verbose_name='phone number'),
        ),
    ]
