# Generated by Django 2.2.10 on 2020-07-13 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20200713_0039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='phone',
            field=models.BigIntegerField(),
        ),
    ]
