# Generated by Django 2.2.10 on 2020-08-31 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_auto_20200813_0030'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccount',
            name='recipient_code',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
