# Generated by Django 2.2.10 on 2020-10-13 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_auto_20201013_2149'),
        ('accounts', '0017_auto_20201013_2205'),
    ]

    operations = [
    ]
