# Generated by Django 2.2.10 on 2020-12-04 18:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_remove_artist_whatsapp_phone'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='artist',
        #     name='whatsapp_phone',
        # ),
        migrations.AlterField(
            model_name='userphoto',
            name='artist',
            field=models.OneToOneField(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Artist'),
        ),
        migrations.AlterField(
            model_name='userphoto',
            name='image',
            field=models.ImageField(
                blank=True, null=True, upload_to='files/profile-pictures'),
        ),
        migrations.AlterField(
            model_name='userphoto',
            name='user',
            field=models.OneToOneField(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
