# Generated by Django 2.2.10 on 2021-05-19 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_auto_20210419_2358'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='artist',
        #     name='whatsapp_phone',
        # ),
        migrations.AddField(
            model_name='bankaccount',
            name='bank_branch',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='bank_iban',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='bank_swift',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='route_no',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='bank_code',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
