# Generated by Django 2.2.10 on 2021-05-19 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_auto_20210519_2145'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='artist',
        #     name='whatsapp_phone',
        # ),
        migrations.AddField(
            model_name='artist',
            name='country_code',
            field=models.CharField(
                blank=True, max_length=5, verbose_name='Country Code'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='country',
            field=models.CharField(
                blank=True, max_length=2, null=True, verbose_name='Country'),
        ),
    ]
