# Generated by Django 2.2.10 on 2021-05-21 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_auto_20210519_2327'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='artist',
        #     name='whatsapp_phone',
        # ),
    ]
