# Generated by Django 2.2.10 on 2021-05-25 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_remove_artist_whatsapp_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='whatsapp_phone',
        ),
    ]
