# Generated by Django 2.2.10 on 2021-05-30 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_remove_artist_whatsapp_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='country',
            field=models.CharField(blank=True, max_length=35, null=True, verbose_name='Country'),
        ),
    ]
