# Generated by Django 2.2.10 on 2021-05-31 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_auto_20210530_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='state',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='State'),
        ),
    ]
