# Generated by Django 2.2.10 on 2021-09-01 20:36

from django.db import migrations, models
import utils.helper


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_auto_20210531_2145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userphoto',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=utils.helper.redefinedFileName),
        ),
    ]
