# Generated by Django 3.0.6 on 2020-06-19 11:59

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=55)),
                ('description', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to='files/artist/songs')),
                ('encoded', models.FileField(blank=True, null=True, upload_to='files/artist/songs/encoded')),
                ('cover', models.ImageField(blank=True, null=True, upload_to='file/artist/songs/covers')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=55)),
                ('description', models.CharField(max_length=100)),
                ('cover', models.ImageField(blank=True, null=True, upload_to='file/artist/songs/covers')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Artist')),
                ('songs', models.ManyToManyField(blank=True, to='songs.Song')),
            ],
        ),
    ]
