# Generated by Django 2.2.10 on 2020-07-23 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0003_auto_20200723_0121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='royaltysplit',
            name='share',
            field=models.FloatField(default=0.0),
        ),
    ]
