# Generated by Django 2.2.10 on 2020-07-23 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0004_auto_20200723_0948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='royaltysplit',
            name='description',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='royaltysplit',
            name='share',
            field=models.FloatField(),
        ),
    ]
