# Generated by Django 2.2.10 on 2020-07-24 00:03

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_artistmeta'),
        ('songs', '0005_auto_20200723_0953'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessAvailability',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('code', models.IntegerField()),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('code', models.IntegerField()),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='album',
            name='eanupc',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='album',
            name='originalReleaseDate',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='song',
            name='album_only',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='song',
            name='disseminated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='song',
            name='explicit',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='song',
            name='isrc',
            field=models.CharField(blank=True, max_length=17, null=True),
        ),
        migrations.AddField(
            model_name='song',
            name='iswc',
            field=models.CharField(blank=True, max_length=17, null=True),
        ),
        migrations.AddField(
            model_name='song',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='SongMeta',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('disseminate_id', models.CharField(blank=True, max_length=10, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('song', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='songs.Song')),
            ],
        ),
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=45)),
                ('disseminate_label_id', models.CharField(blank=True, max_length=11, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('artist', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Artist')),
            ],
        ),
        migrations.AddField(
            model_name='album',
            name='label',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='songs.Label'),
        ),
        migrations.AddField(
            model_name='song',
            name='access_availability',
            field=models.ManyToManyField(blank=True, to='songs.AccessAvailability'),
        ),
        migrations.AddField(
            model_name='song',
            name='genres',
            field=models.ManyToManyField(blank=True, to='songs.Genre'),
        ),
    ]
