# Generated by Django 2.2.10 on 2020-07-24 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0006_auto_20200724_0003'),
    ]

    operations = [
        migrations.AddField(
            model_name='label',
            name='description',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
