# Generated by Django 2.2.10 on 2020-07-24 11:25

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0007_label_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlbumMeta',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('distribute_id', models.CharField(blank=True, max_length=11, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('album', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='songs.Album')),
            ],
        ),
    ]
