# Generated by Django 2.2.10 on 2020-08-13 00:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
        ('songs', '0008_albummeta'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='subscription',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='subscriptions.ArtistSubscription'),
        ),
    ]
