# Generated by Django 2.2.10 on 2020-09-14 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0010_auto_20200831_0226'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='duration_in_ms',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='songmeta',
            name='djm_fingerprint_id',
            field=models.CharField(blank=True, max_length=35, null=True),
        ),
    ]
