# Generated by Django 2.2.10 on 2020-10-22 16:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0012_song_file_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='SongRole',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('code', models.IntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='song',
            name='roles',
            field=models.ManyToManyField(blank=True, to='songs.SongRole'),
        ),
    ]
