# Generated by Django 2.2.10 on 2020-10-22 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0013_auto_20201022_1632'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='roles',
        ),
        migrations.DeleteModel(
            name='SongRole',
        ),
    ]
