# Generated by Django 2.2.10 on 2020-11-12 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0014_auto_20201022_1942'),
    ]

    operations = [
        migrations.AddField(
            model_name='albummeta',
            name='disseminated',
            field=models.BooleanField(default=False),
        ),
    ]
