# Generated by Django 2.2.10 on 2020-11-25 08:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0004_auto_20201112_2124'),
        ('songs', '0015_albummeta_disseminated'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='subscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='subscriptions.ArtistSubscription'),
        ),
        migrations.AlterField(
            model_name='song',
            name='subscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='subscriptions.ArtistSubscription'),
        ),
    ]
