# Generated by Django 2.2.10 on 2020-11-25 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0016_auto_20201125_0825'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='lyrics',
            field=models.TextField(blank=True, null=True),
        ),
    ]
