# Generated by Django 2.2.10 on 2021-01-29 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0017_song_lyrics'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='arranger',
            field=models.CharField(blank=True, max_length=35, null=True),
        ),
        migrations.AddField(
            model_name='song',
            name='composer',
            field=models.CharField(blank=True, max_length=35, null=True),
        ),
        migrations.AddField(
            model_name='song',
            name='publisher',
            field=models.CharField(blank=True, max_length=35, null=True),
        ),
        migrations.AddField(
            model_name='song',
            name='upc',
            field=models.CharField(blank=True, max_length=17, null=True),
        ),
        migrations.AddField(
            model_name='song',
            name='version',
            field=models.CharField(blank=True, max_length=35, null=True),
        ),
        migrations.AddField(
            model_name='song',
            name='writer',
            field=models.CharField(blank=True, max_length=35, null=True),
        ),
    ]
