# Generated by Django 2.2.10 on 2021-05-21 20:23

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0018_auto_20210129_1357'),
    ]

    operations = [
        migrations.CreateModel(
            name='RadioMonitor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('query_date', models.DateField()),
                ('data', jsonfield.fields.JSONField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='songs.Song')),
            ],
        ),
    ]
