# Generated by Django 2.2.10 on 2021-05-26 18:57

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0020_songlink'),
    ]

    operations = [
        migrations.CreateModel(
            name='RadioPlay',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('radio_name', models.CharField(max_length=150)),
                ('radio_id', models.CharField(max_length=150)),
                ('query_date', models.DateField()),
                ('duration', models.DurationField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='songs.Song')),
            ],
        ),
        migrations.DeleteModel(
            name='RadioMonitor',
        ),
    ]
