# Generated by Django 4.2.3 on 2023-09-20 20:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("songs", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("royalty", "0001_initial"),
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Charge",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=75)),
                (
                    "description",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("amount", models.FloatField()),
                (
                    "charge_type",
                    models.CharField(
                        choices=[("PERCENTAGE", "PERCENTAGE"), ("FLAT", "FLAT")],
                        max_length=15,
                    ),
                ),
                ("max_fee", models.FloatField(default=0)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Payout",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("payment_approved", models.BooleanField(default=False)),
                ("amount", models.FloatField(blank=True, null=True)),
                ("approval_timestamp", models.DateTimeField(null=True)),
                ("song_tracked_count", models.IntegerField(default=0)),
                ("triggered", models.BooleanField(default=False)),
                ("last_triggered", models.DateTimeField(null=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "confirm_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PayoutDue",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("due_date", models.DateField(unique=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="SongSales",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("revenue", models.FloatField(default=0)),
                ("deduction", models.FloatField(default=0)),
                ("played_count", models.IntegerField(default=0)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "pay_due",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="payouts.payoutdue",
                    ),
                ),
                (
                    "song",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="songs.song"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RoyaltyPayout",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("amount", models.FloatField(null=True)),
                ("deduction", models.FloatField(default=0)),
                ("is_processing", models.BooleanField(default=False)),
                (
                    "transaction_id",
                    models.CharField(blank=True, max_length=25, null=True, unique=True),
                ),
                ("paid", models.BooleanField(default=False)),
                ("failed", models.BooleanField(default=False)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "pay_due",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="payouts.payoutdue",
                    ),
                ),
                (
                    "royalty",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="royalty.royalty",
                    ),
                ),
                (
                    "royalty_split",
                    models.ManyToManyField(blank=True, to="songs.royaltysplit"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PayoutHistory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("total_paid", models.FloatField(default=0)),
                ("paid_artists", models.IntegerField(default=0)),
                ("paid_artist_royalty", models.IntegerField(default=0)),
                ("gross", models.FloatField(default=0)),
                ("artists_count", models.IntegerField(default=0)),
                ("royalty_count", models.IntegerField(default=0)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "payout",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT, to="payouts.payout"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="payout",
            name="pay_due",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="payouts.payoutdue",
            ),
        ),
        migrations.CreateModel(
            name="ArtistPayout",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("net_profit", models.FloatField(default=0)),
                ("gross_profit", models.FloatField(default=0)),
                ("total_deduction", models.FloatField(default=0)),
                ("royalty_cut", models.FloatField(default=0)),
                ("paid", models.BooleanField(default=False)),
                ("failed", models.BooleanField(default=False)),
                ("is_processing", models.BooleanField(default=False)),
                (
                    "transaction_id",
                    models.CharField(blank=True, max_length=50, null=True, unique=True),
                ),
                (
                    "transaction_reference",
                    models.CharField(blank=True, max_length=25, null=True),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "artist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="accounts.artist",
                    ),
                ),
                (
                    "pay_due",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="payouts.payoutdue",
                    ),
                ),
            ],
        ),
    ]
