# Generated by Django 2.2.10 on 2020-08-31 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payouts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='royaltypayout',
            name='song_sale',
        ),
    ]
