# Generated by Django 4.2.3 on 2023-08-22 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("payouts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="payout",
            name="pay_due",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="payouts.payoutdue",
            ),
        ),
    ]
