# Generated by Django 2.2.10 on 2020-08-31 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payouts', '0002_remove_royaltypayout_song_sale'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='songsales',
            name='paid',
        ),
        migrations.AddField(
            model_name='artistpayout',
            name='transaction_reference',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='payout',
            name='song_tracked_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='payouthistory',
            name='paid_artist_royalty',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='payouthistory',
            name='royalty_count',
            field=models.IntegerField(default=0),
        ),
    ]
