# Generated by Django 2.2.10 on 2020-10-13 21:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payouts', '0003_auto_20200831_1818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='songsales',
            name='song',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='songs.Song'),
        ),
    ]
