# Generated by Django 2.2.10 on 2020-10-13 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payouts', '0004_auto_20201013_2205'),
        ('payouts', '0004_auto_20201013_2149'),
    ]

    operations = [
    ]
