# Generated by Django 4.2.3 on 2023-08-22 11:49

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("payouts", "0004_payout"),
    ]

    operations = [
        migrations.CreateModel(
            name="PayoutHistory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("total_paid", models.FloatField(default=0)),
                ("paid_artists", models.IntegerField(default=0)),
                ("paid_artist_royalty", models.IntegerField(default=0)),
                ("gross", models.FloatField(default=0)),
                ("artists_count", models.IntegerField(default=0)),
                ("royalty_count", models.IntegerField(default=0)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "payout",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT, to="payouts.payout"
                    ),
                ),
            ],
        ),
    ]
