# Generated by Django 2.2.10 on 2020-12-27 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payouts', '0005_merge_20201013_2209'),
    ]

    operations = [
        migrations.AddField(
            model_name='artistpayout',
            name='is_processing',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='artistpayout',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
