# Generated by Django 2.2.10 on 2020-12-27 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payouts', '0007_auto_20201227_2005'),
    ]

    operations = [
        migrations.AddField(
            model_name='royaltypayout',
            name='is_processing',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='royaltypayout',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=25, null=True, unique=True),
        ),
    ]
