# Generated by Django 2.2.10 on 2021-08-10 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payouts', '0009_auto_20210809_2213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artistpayout',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
