# Generated by Django 2.2.10 on 2020-08-29 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_auto_20200813_0034'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artistsubscription',
            old_name='cancel',
            new_name='expired',
        ),
        migrations.RenameField(
            model_name='artistsubscription',
            old_name='cancel_timestamp',
            new_name='expired_timestamp',
        ),
    ]
