# Generated by Django 2.2.10 on 2020-11-12 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0003_auto_20200829_0228'),
    ]

    operations = [
        migrations.AddField(
            model_name='artistsubscription',
            name='activated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='artistsubscription',
            name='eveara_id',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
