# Generated by Django 2.2.10 on 2021-02-24 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0005_package_sku_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='eveara_id',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
