# Generated by Django 2.2.10 on 2021-05-19 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0006_package_eveara_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptiontransaction',
            name='transaction_reference',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
