# Generated by Django 2.2.10 on 2021-06-18 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0008_auto_20210529_2350'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='feature',
            field=models.CharField(choices=[('GO_DISTRO', 'Go Distro'), ('GO_MONITOR', 'Go Monitor')], default='GO_DISTRO', max_length=50),
        ),
    ]
