# Generated by Django 2.2.10 on 2021-01-29 15:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('systemcontrol', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('eveara_user_id', models.CharField(max_length=75)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
