# Generated by Django 2.2.10 on 2020-07-23 01:21

from django.db import migrations, models
import django.db.models.deletion
import royalty.managers
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Royalty',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('is_active', models.BooleanField(default=False)),
                ('phone', models.CharField(max_length=15)),
                ('last_authenticated', models.DateTimeField(null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            managers=[
                ('objects', royalty.managers.RoyaltyManager()),
            ],
        ),
        migrations.CreateModel(
            name='RoyaltyProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(blank=True, max_length=45, null=True)),
                ('last_name', models.CharField(blank=True, max_length=45, null=True)),
                ('other_names', models.CharField(blank=True, max_length=45, null=True)),
                ('bio', models.CharField(max_length=100)),
                ('account_number', models.CharField(blank=True, max_length=19, null=True)),
                ('bvn', models.CharField(blank=True, max_length=19, null=True)),
                ('bank_name', models.CharField(blank=True, max_length=75, null=True)),
                ('bank_code', models.CharField(blank=True, max_length=10, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('royalty', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='royalty.Royalty')),
            ],
        ),
    ]
