# Generated by Django 2.2.10 on 2020-07-23 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('royalty', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='royalty',
            old_name='email',
            new_name='username',
        ),
    ]
