# Generated by Django 2.2.10 on 2020-08-31 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('royalty', '0002_auto_20200723_1226'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='royaltyprofile',
            name='bvn',
        ),
        migrations.AddField(
            model_name='royaltyprofile',
            name='recipient_code',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
