# Generated by Django 4.2.3 on 2023-08-22 11:05

from django.db import migrations, models
import django.db.models.deletion
import sso.tasks
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="IdentityApp",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=75)),
                (
                    "description",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("redirect_url", models.URLField()),
                (
                    "private_key",
                    models.CharField(
                        db_index=True, default=sso.tasks.secret_key_gen, max_length=128
                    ),
                ),
                (
                    "public_key",
                    models.CharField(
                        db_index=True, default=sso.tasks.secret_key_gen, max_length=128
                    ),
                ),
                ("last_modified", models.DateTimeField(auto_now=True)),
                ("date_created", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="AppAuthLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("accessToken", models.CharField(db_index=True, max_length=255)),
                ("client_ip", models.CharField(max_length=15)),
                ("client_user_agent", models.CharField(max_length=255)),
                ("app_ip", models.CharField(max_length=15, null=True)),
                ("approval_request_count", models.IntegerField(default=0)),
                ("app_user_agent", models.CharField(max_length=255, null=True)),
                ("approval_request_timestamp", models.DateTimeField(null=True)),
                ("last_request_timestamp", models.DateTimeField(auto_now=True)),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                (
                    "artist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.artist",
                    ),
                ),
                (
                    "identity_app",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="sso.identityapp",
                    ),
                ),
            ],
        ),
    ]
