# Generated by Django 2.2.10 on 2021-09-25 01:00

from django.db import migrations, models
import sso.tasks


class Migration(migrations.Migration):

    dependencies = [
        ('sso', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='identityapp',
            name='private_key',
            field=models.CharField(db_index=True, default=sso.tasks.secret_key_gen, max_length=128),
        ),
        migrations.AlterField(
            model_name='identityapp',
            name='public_key',
            field=models.CharField(db_index=True, default=sso.tasks.secret_key_gen, max_length=128),
        ),
    ]
